name: "GitHub Actions - Testing"
on:
  push:

jobs:
  ubuntu-testing:
    runs-on: ubuntu-latest
    steps:
      - name: ubuntu-set-output-0
        id: ubuntu-test-0
        run: |
          echo ::set-output name=test::"Ubuntu Test set-output"

      - name: ubuntu-set-output-1
        run: |
          echo "Hello from ${{steps.ubuntu-test-0.outputs.test}}"

      - name: ubuntu-github-output-0
        id: ubuntu-test-1
        run: |
          echo test="Ubuntu Github Output Test 0" >> $GITHUB_OUTPUT

      - name: ubuntu-github-output-1
        run: |
          echo "Hello from ${{steps.ubuntu-test-1.outputs.test}}"

      - name: ubuntu-github-output-1
        run: |
          echo action_echo="disabled" >> $GITHUB_OUTPUT
          echo "::echo::on"
          echo action_echo="enabled" >> $GITHUB_OUTPUT
          echo "::echo::off"
          echo action_echo="disabled" >> $GITHUB_OUTPUT


  windows-testing:
    runs-on: windows-latest
    steps:
      - name: windows-set-output-0
        id: windows-test-0
        run: |
          write-output ::set-output name=test::"Windows Test set-output"

      - name: windows-set-output-1
        run: |
          write-output "Hello from ${{steps.windows-test-0.outputs.test}}"

      - name: windows-github-output-0
        id: windows-test-1
        run: |
          write-output test="Windows Github Output Test 0" >> $GITHUB_OUTPUT

      - name: windows-github-output-1
        run: |
          write-output "Hello from ${{steps.windows-test-1.outputs.test}}"

      - name: windows-github-output-1
        run: |
          write-output action_echo="disabled" >> $GITHUB_OUTPUT
          write-output "::echo::on"
          write-output action_echo="enabled" >> $GITHUB_OUTPUT
          write-output "::echo::off"
          write-output action_echo="disabled" >> $GITHUB_OUTPUT



